/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { version1EnginesFetchList } from "../funcs/version1EnginesFetchList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Engines extends ClientSDK {
  /**
   * List engines
   *
   * @remarks
   * List all engines available to your organization/user
   */
  async fetchList(
    request: operations.FetchListRequest,
    options?: RequestOptions,
  ): Promise<Array<components.Engine>> {
    return unwrapAsync(version1EnginesFetchList(
      this,
      request,
      options,
    ));
  }
}
