/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Version1 } from "./version1.js";

export class StabilityAIClient extends ClientSDK {
  private _version1?: Version1;
  get version1(): Version1 {
    return (this._version1 ??= new Version1(this._options));
  }
}
