workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    StabilityAI REST API:
        inputs:
            - location: openapi.json
        registry:
            location: registry.speakeasyapi.dev/amd/stabilityai-client-typescript/stability-ai-rest-api
targets:
    stabilityai-client-typescript:
        target: typescript
        source: StabilityAI REST API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/amd/stabilityai-client-typescript/stability-ai-rest-api-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
