/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FetchBalanceRequest = {
  /**
   * Allows for requests to be scoped to an organization other than the user's default.  If not provided, the user's default organization will be used.
   */
  organization?: string | undefined;
  /**
   * Used to identify the source of requests, such as the client application or sub-organization. Optional, but recommended for organizational clarity.
   */
  stabilityClientID?: string | undefined;
  /**
   * Used to identify the version of the application or service making the requests. Optional, but recommended for organizational clarity.
   */
  stabilityClientVersion?: string | undefined;
};

/** @internal */
export const FetchBalanceRequest$inboundSchema: z.ZodType<
  FetchBalanceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Organization: z.string().optional(),
  "Stability-Client-ID": z.string().optional(),
  "Stability-Client-Version": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Organization": "organization",
    "Stability-Client-ID": "stabilityClientID",
    "Stability-Client-Version": "stabilityClientVersion",
  });
});

/** @internal */
export type FetchBalanceRequest$Outbound = {
  Organization?: string | undefined;
  "Stability-Client-ID"?: string | undefined;
  "Stability-Client-Version"?: string | undefined;
};

/** @internal */
export const FetchBalanceRequest$outboundSchema: z.ZodType<
  FetchBalanceRequest$Outbound,
  z.ZodTypeDef,
  FetchBalanceRequest
> = z.object({
  organization: z.string().optional(),
  stabilityClientID: z.string().optional(),
  stabilityClientVersion: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    organization: "Organization",
    stabilityClientID: "Stability-Client-ID",
    stabilityClientVersion: "Stability-Client-Version",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchBalanceRequest$ {
  /** @deprecated use `FetchBalanceRequest$inboundSchema` instead. */
  export const inboundSchema = FetchBalanceRequest$inboundSchema;
  /** @deprecated use `FetchBalanceRequest$outboundSchema` instead. */
  export const outboundSchema = FetchBalanceRequest$outboundSchema;
  /** @deprecated use `FetchBalanceRequest$Outbound` instead. */
  export type Outbound = FetchBalanceRequest$Outbound;
}

export function fetchBalanceRequestToJSON(
  fetchBalanceRequest: FetchBalanceRequest,
): string {
  return JSON.stringify(
    FetchBalanceRequest$outboundSchema.parse(fetchBalanceRequest),
  );
}

export function fetchBalanceRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchBalanceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchBalanceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchBalanceRequest' from JSON`,
  );
}
