/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ClipGuidancePreset = {
  FastBlue: "FAST_BLUE",
  FastGreen: "FAST_GREEN",
  None: "NONE",
  Simple: "SIMPLE",
  Slow: "SLOW",
  Slower: "SLOWER",
  Slowest: "SLOWEST",
} as const;
export type ClipGuidancePreset = ClosedEnum<typeof ClipGuidancePreset>;

/** @internal */
export const ClipGuidancePreset$inboundSchema: z.ZodNativeEnum<
  typeof ClipGuidancePreset
> = z.nativeEnum(ClipGuidancePreset);

/** @internal */
export const ClipGuidancePreset$outboundSchema: z.ZodNativeEnum<
  typeof ClipGuidancePreset
> = ClipGuidancePreset$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClipGuidancePreset$ {
  /** @deprecated use `ClipGuidancePreset$inboundSchema` instead. */
  export const inboundSchema = ClipGuidancePreset$inboundSchema;
  /** @deprecated use `ClipGuidancePreset$outboundSchema` instead. */
  export const outboundSchema = ClipGuidancePreset$outboundSchema;
}
