/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InitImage = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const InitImage$inboundSchema: z.ZodType<
  InitImage,
  z.ZodTypeDef,
  unknown
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/** @internal */
export type InitImage$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const InitImage$outboundSchema: z.ZodType<
  InitImage$Outbound,
  z.ZodTypeDef,
  InitImage
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InitImage$ {
  /** @deprecated use `InitImage$inboundSchema` instead. */
  export const inboundSchema = InitImage$inboundSchema;
  /** @deprecated use `InitImage$outboundSchema` instead. */
  export const outboundSchema = InitImage$outboundSchema;
  /** @deprecated use `InitImage$Outbound` instead. */
  export type Outbound = InitImage$Outbound;
}

export function initImageToJSON(initImage: InitImage): string {
  return JSON.stringify(InitImage$outboundSchema.parse(initImage));
}

export function initImageFromJSON(
  jsonString: string,
): SafeParseResult<InitImage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InitImage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InitImage' from JSON`,
  );
}
