/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Whether to use `image_strength` or `step_schedule_*` to control how much influence the `init_image` has on the result.
 */
export const InitImageMode = {
  ImageStrength: "IMAGE_STRENGTH",
  StepSchedule: "STEP_SCHEDULE",
} as const;
/**
 * Whether to use `image_strength` or `step_schedule_*` to control how much influence the `init_image` has on the result.
 */
export type InitImageMode = ClosedEnum<typeof InitImageMode>;

/** @internal */
export const InitImageMode$inboundSchema: z.ZodNativeEnum<
  typeof InitImageMode
> = z.nativeEnum(InitImageMode);

/** @internal */
export const InitImageMode$outboundSchema: z.ZodNativeEnum<
  typeof InitImageMode
> = InitImageMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InitImageMode$ {
  /** @deprecated use `InitImageMode$inboundSchema` instead. */
  export const inboundSchema = InitImageMode$inboundSchema;
  /** @deprecated use `InitImageMode$outboundSchema` instead. */
  export const outboundSchema = InitImageMode$outboundSchema;
}
